set(_CATKIN_CURRENT_PACKAGE "freefloating_gazebo")
set(freefloating_gazebo_VERSION "1.1.0")
set(freefloating_gazebo_MAINTAINER "Olivier Kermorgant <olivier_kermorgant@yahoo.fr>")
set(freefloating_gazebo_PACKAGE_FORMAT "2")
set(freefloating_gazebo_BUILD_DEPENDS "cmake_modules" "urdf" "gazebo_ros" "control_toolbox" "rostime" "roscpp" "std_msgs" "std_srvs" "gazebo_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs" "eigen")
set(freefloating_gazebo_BUILD_EXPORT_DEPENDS "cmake_modules" "urdf" "gazebo_ros" "control_toolbox" "rostime" "roscpp" "std_msgs" "std_srvs" "gazebo_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs" "eigen")
set(freefloating_gazebo_BUILDTOOL_DEPENDS "catkin")
set(freefloating_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(freefloating_gazebo_EXEC_DEPENDS "cmake_modules" "urdf" "gazebo_ros" "control_toolbox" "rostime" "roscpp" "std_msgs" "std_srvs" "gazebo_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs" "eigen")
set(freefloating_gazebo_RUN_DEPENDS "cmake_modules" "urdf" "gazebo_ros" "control_toolbox" "rostime" "roscpp" "std_msgs" "std_srvs" "gazebo_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs" "eigen")
set(freefloating_gazebo_TEST_DEPENDS )
set(freefloating_gazebo_DOC_DEPENDS )
set(freefloating_gazebo_DEPRECATED "")