# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tunepid.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TunePID(object):
    def setupUi(self, TunePID):
        TunePID.setObjectName("TunePID")
        TunePID.resize(1272, 807)
        self.centralWidget = QtWidgets.QWidget(TunePID)
        self.centralWidget.setObjectName("centralWidget")
        self.p_save = QtWidgets.QPushButton(self.centralWidget)
        self.p_save.setGeometry(QtCore.QRect(290, 130, 131, 22))
        self.p_save.setObjectName("p_save")
        self.p_Kp_slider = QtWidgets.QSlider(self.centralWidget)
        self.p_Kp_slider.setGeometry(QtCore.QRect(50, 60, 471, 21))
        self.p_Kp_slider.setMaximum(1000)
        self.p_Kp_slider.setOrientation(QtCore.Qt.Horizontal)
        self.p_Kp_slider.setObjectName("p_Kp_slider")
        self.axes_list = QtWidgets.QComboBox(self.centralWidget)
        self.axes_list.setGeometry(QtCore.QRect(490, 20, 79, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axes_list.sizePolicy().hasHeightForWidth())
        self.axes_list.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.axes_list.setFont(font)
        self.axes_list.setObjectName("axes_list")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 31, 16))
        self.label.setObjectName("label")
        self.p_Kp = QtWidgets.QLabel(self.centralWidget)
        self.p_Kp.setGeometry(QtCore.QRect(530, 60, 59, 14))
        self.p_Kp.setObjectName("p_Kp")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 31, 16))
        self.label_2.setObjectName("label_2")
        self.p_Ki_slider = QtWidgets.QSlider(self.centralWidget)
        self.p_Ki_slider.setGeometry(QtCore.QRect(50, 80, 471, 21))
        self.p_Ki_slider.setMaximum(1000)
        self.p_Ki_slider.setOrientation(QtCore.Qt.Horizontal)
        self.p_Ki_slider.setObjectName("p_Ki_slider")
        self.p_Ki = QtWidgets.QLabel(self.centralWidget)
        self.p_Ki.setGeometry(QtCore.QRect(530, 80, 59, 14))
        self.p_Ki.setObjectName("p_Ki")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 31, 16))
        self.label_3.setObjectName("label_3")
        self.p_Kd_slider = QtWidgets.QSlider(self.centralWidget)
        self.p_Kd_slider.setGeometry(QtCore.QRect(50, 100, 471, 21))
        self.p_Kd_slider.setMaximum(1000)
        self.p_Kd_slider.setOrientation(QtCore.Qt.Horizontal)
        self.p_Kd_slider.setObjectName("p_Kd_slider")
        self.p_Kd = QtWidgets.QLabel(self.centralWidget)
        self.p_Kd.setGeometry(QtCore.QRect(530, 100, 59, 14))
        self.p_Kd.setObjectName("p_Kd")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(600, 60, 31, 16))
        self.label_4.setObjectName("label_4")
        self.v_Ki = QtWidgets.QLabel(self.centralWidget)
        self.v_Ki.setGeometry(QtCore.QRect(1120, 80, 59, 14))
        self.v_Ki.setObjectName("v_Ki")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(600, 100, 31, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(600, 80, 31, 16))
        self.label_6.setObjectName("label_6")
        self.v_Kp_slider = QtWidgets.QSlider(self.centralWidget)
        self.v_Kp_slider.setGeometry(QtCore.QRect(640, 60, 471, 21))
        self.v_Kp_slider.setMaximum(1000)
        self.v_Kp_slider.setOrientation(QtCore.Qt.Horizontal)
        self.v_Kp_slider.setObjectName("v_Kp_slider")
        self.v_Ki_slider = QtWidgets.QSlider(self.centralWidget)
        self.v_Ki_slider.setGeometry(QtCore.QRect(640, 80, 471, 21))
        self.v_Ki_slider.setMaximum(1000)
        self.v_Ki_slider.setOrientation(QtCore.Qt.Horizontal)
        self.v_Ki_slider.setObjectName("v_Ki_slider")
        self.v_Kp = QtWidgets.QLabel(self.centralWidget)
        self.v_Kp.setGeometry(QtCore.QRect(1120, 60, 59, 14))
        self.v_Kp.setObjectName("v_Kp")
        self.v_Kd_slider = QtWidgets.QSlider(self.centralWidget)
        self.v_Kd_slider.setGeometry(QtCore.QRect(640, 100, 471, 21))
        self.v_Kd_slider.setMaximum(1000)
        self.v_Kd_slider.setOrientation(QtCore.Qt.Horizontal)
        self.v_Kd_slider.setObjectName("v_Kd_slider")
        self.v_Kd = QtWidgets.QLabel(self.centralWidget)
        self.v_Kd.setGeometry(QtCore.QRect(1120, 100, 59, 14))
        self.v_Kd.setObjectName("v_Kd")
        self.tofile = QtWidgets.QPushButton(self.centralWidget)
        self.tofile.setGeometry(QtCore.QRect(600, 20, 80, 22))
        self.tofile.setObjectName("tofile")
        self.v_save = QtWidgets.QPushButton(self.centralWidget)
        self.v_save.setGeometry(QtCore.QRect(990, 130, 131, 22))
        self.v_save.setObjectName("v_save")
        self.p_cascaded = QtWidgets.QCheckBox(self.centralWidget)
        self.p_cascaded.setGeometry(QtCore.QRect(430, 130, 141, 20))
        self.p_cascaded.setObjectName("p_cascaded")
        self.p_Kp_2 = QtWidgets.QLabel(self.centralWidget)
        self.p_Kp_2.setGeometry(QtCore.QRect(450, 20, 31, 16))
        self.p_Kp_2.setObjectName("p_Kp_2")
        self.p_setpoint = QtWidgets.QSlider(self.centralWidget)
        self.p_setpoint.setGeometry(QtCore.QRect(80, 130, 131, 21))
        self.p_setpoint.setMaximum(1000)
        self.p_setpoint.setOrientation(QtCore.Qt.Horizontal)
        self.p_setpoint.setObjectName("p_setpoint")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 61, 16))
        self.label_7.setObjectName("label_7")
        self.v_setpoint = QtWidgets.QSlider(self.centralWidget)
        self.v_setpoint.setGeometry(QtCore.QRect(670, 130, 141, 21))
        self.v_setpoint.setMaximum(1000)
        self.v_setpoint.setOrientation(QtCore.Qt.Horizontal)
        self.v_setpoint.setObjectName("v_setpoint")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(600, 130, 61, 16))
        self.label_8.setObjectName("label_8")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 160, 561, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.p_sim = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.p_sim.setContentsMargins(11, 11, 11, 11)
        self.p_sim.setSpacing(6)
        self.p_sim.setObjectName("p_sim")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(620, 160, 551, 571))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.v_sim = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.v_sim.setContentsMargins(11, 11, 11, 11)
        self.v_sim.setSpacing(6)
        self.v_sim.setObjectName("v_sim")
        self.v_sp = QtWidgets.QLabel(self.centralWidget)
        self.v_sp.setGeometry(QtCore.QRect(850, 130, 59, 14))
        self.v_sp.setObjectName("v_sp")
        self.p_sp = QtWidgets.QLabel(self.centralWidget)
        self.p_sp.setGeometry(QtCore.QRect(220, 130, 59, 14))
        self.p_sp.setObjectName("p_sp")
        self.p_tofile = QtWidgets.QPushButton(self.centralWidget)
        self.p_tofile.setGeometry(QtCore.QRect(170, 20, 181, 22))
        self.p_tofile.setObjectName("p_tofile")
        self.v_tofile = QtWidgets.QPushButton(self.centralWidget)
        self.v_tofile.setGeometry(QtCore.QRect(780, 20, 181, 22))
        self.v_tofile.setObjectName("v_tofile")
        self.time_slider = QtWidgets.QSlider(self.centralWidget)
        self.time_slider.setGeometry(QtCore.QRect(330, 740, 541, 21))
        self.time_slider.setMinimum(1)
        self.time_slider.setMaximum(1000)
        self.time_slider.setOrientation(QtCore.Qt.Horizontal)
        self.time_slider.setObjectName("time_slider")
        TunePID.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(TunePID)
        self.mainToolBar.setObjectName("mainToolBar")
        TunePID.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(TunePID)
        self.statusBar.setObjectName("statusBar")
        TunePID.setStatusBar(self.statusBar)

        self.retranslateUi(TunePID)
        QtCore.QMetaObject.connectSlotsByName(TunePID)

    def retranslateUi(self, TunePID):
        _translate = QtCore.QCoreApplication.translate
        TunePID.setWindowTitle(_translate("TunePID", "TunePID"))
        self.p_save.setText(_translate("TunePID", "Save position gains"))
        self.label.setText(_translate("TunePID", "Kp"))
        self.p_Kp.setText(_translate("TunePID", "0"))
        self.label_2.setText(_translate("TunePID", "Ki"))
        self.p_Ki.setText(_translate("TunePID", "0"))
        self.label_3.setText(_translate("TunePID", "Kd"))
        self.p_Kd.setText(_translate("TunePID", "0"))
        self.label_4.setText(_translate("TunePID", "Kp"))
        self.v_Ki.setText(_translate("TunePID", "0"))
        self.label_5.setText(_translate("TunePID", "Kd"))
        self.label_6.setText(_translate("TunePID", "Ki"))
        self.v_Kp.setText(_translate("TunePID", "0"))
        self.v_Kd.setText(_translate("TunePID", "0"))
        self.tofile.setText(_translate("TunePID", "Save to file"))
        self.v_save.setText(_translate("TunePID", "Save velocity gains"))
        self.p_cascaded.setText(_translate("TunePID", "Cascaded position"))
        self.p_Kp_2.setText(_translate("TunePID", "Axis"))
        self.label_7.setText(_translate("TunePID", "Setpoint"))
        self.label_8.setText(_translate("TunePID", "Setpoint"))
        self.v_sp.setText(_translate("TunePID", "0"))
        self.p_sp.setText(_translate("TunePID", "0"))
        self.p_tofile.setText(_translate("TunePID", "Save position gains to file"))
        self.v_tofile.setText(_translate("TunePID", "Save velocity gains to file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TunePID = QtWidgets.QMainWindow()
    ui = Ui_TunePID()
    ui.setupUi(TunePID)
    TunePID.show()
    sys.exit(app.exec_())

