#!/bin/bash
scenarioNumber=1
if [ -z "$1" ]; then
	echo "Scenario number not specified! Please inform scenario number (1, 2 or 3):";
	read number
	menor=1
	maior=3
	if [ $number -lt $menor -o $number -gt $maior ]; then
		echo "Invalid number...  Using scenario 1"
	fi
else
	scenarioNumber=$1;
fi

echo "Updating installed files. Please wait...";
catkin_make_isolated --install -q --pkg usv_sim usv_water_current usv_wind_current usv_navigation usv_base_ctrl >/dev/null
echo "Parsing files for scenario $1. Please wait...";
roslaunch usv_sim airboat_scenario.launch parse:=true  scenario:="$scenarioNumber"
echo "Starting simulation of scenario $1";
roslaunch usv_sim airboat_scenario.launch parse:=false scenario:="$scenarioNumber"
