#!/bin/bash

echo "Updating installed files. Please wait...";
catkin_make_isolated --install -q --pkg usv_sim usv_water_current usv_wind_current usv_navigation usv_base_ctrl usv_sailing_plugin
echo "Parsing files for scenario 4. Please wait...";
roslaunch usv_sim rudderboat_scenario4.launch parse:=true  
echo "Starting simulation of scenario 4";
roslaunch usv_sim rudderboat_scenario4.launch parse:=false
