#!/bin/bash

echo "Updating installed files. Please wait...";
catkin_make_isolated --install -q --pkg usv_sim usv_water_current usv_wind_current usv_navigation usv_base_ctrl usv_sailing_plugin
echo "Parsing files for polar diagram. Please wait...";
roslaunch usv_sim sailboat_polar_diagram.launch parse:=true  
echo "Starting simulation of polar diagram";
roslaunch usv_sim sailboat_polar_diagram.launch parse:=false gui:=false
