set(_CATKIN_CURRENT_PACKAGE "osg_interactive_markers")
set(osg_interactive_markers_VERSION "1.0.2")
set(osg_interactive_markers_MAINTAINER "Javier Perez <japerez@uji.es>")
set(osg_interactive_markers_PACKAGE_FORMAT "1")
set(osg_interactive_markers_BUILD_DEPENDS "roscpp" "libopenscenegraph" "visualization_msgs" "tf" "osg_utils" "osg_markers" "interactive_markers")
set(osg_interactive_markers_BUILD_EXPORT_DEPENDS "roscpp" "libopenscenegraph" "visualization_msgs" "tf" "osg_utils" "osg_markers" "interactive_markers")
set(osg_interactive_markers_BUILDTOOL_DEPENDS "catkin")
set(osg_interactive_markers_BUILDTOOL_EXPORT_DEPENDS )
set(osg_interactive_markers_EXEC_DEPENDS "roscpp" "libopenscenegraph" "visualization_msgs" "tf" "osg_utils" "osg_markers" "interactive_markers")
set(osg_interactive_markers_RUN_DEPENDS "roscpp" "libopenscenegraph" "visualization_msgs" "tf" "osg_utils" "osg_markers" "interactive_markers")
set(osg_interactive_markers_TEST_DEPENDS )
set(osg_interactive_markers_DOC_DEPENDS )
set(osg_interactive_markers_DEPRECATED "")