#!/bin/bash

echo "Updating installed files. Please wait...";
catkin_make_isolated --install -q --pkg usv_sim usv_water_current usv_wind_current usv_navigation usv_base_ctrl usv_sailing_plugin
echo "Parsing files for empty scenario. Please wait...";
roslaunch usv_sim sailboat_empty_scenario.launch parse:=true  
echo "Starting simulation of empty scenario";
roslaunch usv_sim sailboat_empty_scenario.launch parse:=false gui:=false
