set(_CATKIN_CURRENT_PACKAGE "first_control")
set(first_control_VERSION "0.0.0")
set(first_control_MAINTAINER "lsa <lsa@todo.todo>")
set(first_control_PACKAGE_FORMAT "1")
set(first_control_BUILD_DEPENDS )
set(first_control_BUILD_EXPORT_DEPENDS )
set(first_control_BUILDTOOL_DEPENDS "catkin")
set(first_control_BUILDTOOL_EXPORT_DEPENDS )
set(first_control_EXEC_DEPENDS )
set(first_control_RUN_DEPENDS )
set(first_control_TEST_DEPENDS )
set(first_control_DOC_DEPENDS )
set(first_control_DEPRECATED "")