# docker image built on top of usv_sim image 
# with packages specific for Intel video cards.
# This is the part that might change according to your hardware. Tweaking dependencies and Googling might be needed !!!!
FROM usv_sim

# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]
 
# according to http://wiki.ros.org/docker/Tutorials/Hardware%20Acceleration
# this is the requirement for Intel video cards
RUN \
  apt-get update && \
  apt-get -y install libgl1-mesa-glx libgl1-mesa-dri mesa-utils && \
  rm -rf /var/lib/apt/lists/*


# Set the working folder at startup
WORKDIR /root/catkin_ws
