set(_CATKIN_CURRENT_PACKAGE "underwater_sensor_msgs")
set(underwater_sensor_msgs_VERSION "1.4.1")
set(underwater_sensor_msgs_MAINTAINER "Mario Prats <marioprats@gmail.com>, Javier Perez <perezsolerj@gmail.com>")
set(underwater_sensor_msgs_PACKAGE_FORMAT "1")
set(underwater_sensor_msgs_BUILD_DEPENDS "roscpp" "message_generation" "std_msgs" "visualization_msgs")
set(underwater_sensor_msgs_BUILD_EXPORT_DEPENDS "roscpp" "message_runtime" "std_msgs" "visualization_msgs")
set(underwater_sensor_msgs_BUILDTOOL_DEPENDS "catkin")
set(underwater_sensor_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(underwater_sensor_msgs_EXEC_DEPENDS "roscpp" "message_runtime" "std_msgs" "visualization_msgs")
set(underwater_sensor_msgs_RUN_DEPENDS "roscpp" "message_runtime" "std_msgs" "visualization_msgs")
set(underwater_sensor_msgs_TEST_DEPENDS )
set(underwater_sensor_msgs_DOC_DEPENDS )
set(underwater_sensor_msgs_DEPRECATED "")