#!/bin/bash

echo "Updating installed files. Please wait...";
catkin_make_isolated --install -q --pkg usv_water_current usv_wind_current usv_navigation usv_base_ctrl usv_scenarios usv_models
echo "Parsing files for scenario 1. Please wait...";
roslaunch usv_scenarios airboat_scenario1.launch parse:=true  
echo "Starting simulation of scenario 1";
roslaunch usv_scenarios airboat_scenario1.launch parse:=false

