#!/bin/bash

echo "Updating installed files. Please wait...";
catkin_make_isolated --install -q --pkg usv_sim usv_water_current usv_wind_current usv_navigation usv_base_ctrl
echo "Parsing files for scenario 6. Please wait...";
roslaunch usv_sim rudderboat_scenario6.launch parse:=true  
echo "Starting simulation of scenario 6";
roslaunch usv_sim rudderboat_scenario6.launch parse:=false gui:=false
