set(_CATKIN_CURRENT_PACKAGE "osg_markers")
set(osg_markers_VERSION "1.0.2")
set(osg_markers_MAINTAINER "Javier Perez <japerez@uji.es>")
set(osg_markers_PACKAGE_FORMAT "1")
set(osg_markers_BUILD_DEPENDS "roscpp" "libopenscenegraph" "visualization_msgs" "tf" "roslib")
set(osg_markers_BUILD_EXPORT_DEPENDS "roscpp" "libopenscenegraph" "visualization_msgs" "tf" "roslib")
set(osg_markers_BUILDTOOL_DEPENDS "catkin")
set(osg_markers_BUILDTOOL_EXPORT_DEPENDS )
set(osg_markers_EXEC_DEPENDS "roscpp" "libopenscenegraph" "visualization_msgs" "tf" "roslib")
set(osg_markers_RUN_DEPENDS "roscpp" "libopenscenegraph" "visualization_msgs" "tf" "roslib")
set(osg_markers_TEST_DEPENDS )
set(osg_markers_DOC_DEPENDS )
set(osg_markers_DEPRECATED "")