#!/bin/bash

echo "Updating installed files. Please wait...";
cd ~/catkin_new_lsa
catkin_make_isolated --install -q --pkg usv_sim
echo "Parsing files for scenario 0. Please wait...";
roslaunch usv_sim sailboat_scenario0.launch parse:=true  
echo "Starting simulation of scenario 0";
roslaunch usv_sim sailboat_scenario0.launch parse:=false