set(_CATKIN_CURRENT_PACKAGE "freefloating_gazebo_demo")
set(freefloating_gazebo_demo_VERSION "1.1.0")
set(freefloating_gazebo_demo_MAINTAINER "Olivier Kermorgant <olivier_kermorgant@yahoo.fr>")
set(freefloating_gazebo_demo_PACKAGE_FORMAT "2")
set(freefloating_gazebo_demo_BUILD_DEPENDS "freefloating_gazebo" "roscpp" "sensor_msgs" "nav_msgs")
set(freefloating_gazebo_demo_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs" "nav_msgs")
set(freefloating_gazebo_demo_BUILDTOOL_DEPENDS "catkin")
set(freefloating_gazebo_demo_BUILDTOOL_EXPORT_DEPENDS )
set(freefloating_gazebo_demo_EXEC_DEPENDS "roscpp" "sensor_msgs" "nav_msgs")
set(freefloating_gazebo_demo_RUN_DEPENDS "roscpp" "sensor_msgs" "nav_msgs")
set(freefloating_gazebo_demo_TEST_DEPENDS )
set(freefloating_gazebo_demo_DOC_DEPENDS )
set(freefloating_gazebo_demo_DEPRECATED "")