set(_CATKIN_CURRENT_PACKAGE "visualization_osg")
set(visualization_osg_VERSION "1.0.2")
set(visualization_osg_MAINTAINER "Javier Perez <japerez@uji.es>")
set(visualization_osg_PACKAGE_FORMAT "1")
set(visualization_osg_BUILD_DEPENDS )
set(visualization_osg_BUILD_EXPORT_DEPENDS "osg_utils" "osg_markers" "osg_interactive_markers")
set(visualization_osg_BUILDTOOL_DEPENDS "catkin")
set(visualization_osg_BUILDTOOL_EXPORT_DEPENDS )
set(visualization_osg_EXEC_DEPENDS "osg_utils" "osg_markers" "osg_interactive_markers")
set(visualization_osg_RUN_DEPENDS "osg_utils" "osg_markers" "osg_interactive_markers")
set(visualization_osg_TEST_DEPENDS )
set(visualization_osg_DOC_DEPENDS )
set(visualization_osg_DEPRECATED "")