(cl:in-package underwater_sensor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          HEADER_DVL-VAL
          HEADER_DVL
          DATE-VAL
          DATE
          SALINITY-VAL
          SALINITY
          TEMPERATURE-VAL
          TEMPERATURE
          DEPTH-VAL
          DEPTH
          SOUND_SPEED-VAL
          SOUND_SPEED
          TEST-VAL
          TEST
          WI_X_AXIS-VAL
          WI_X_AXIS
          WI_Y_AXIS-VAL
          WI_Y_AXIS
          WI_Z_AXIS-VAL
          WI_Z_AXIS
          WI_ERROR-VAL
          WI_ERROR
          WI_STATUS-VAL
          WI_STATUS
          BI_X_AXIS-VAL
          BI_X_AXIS
          BI_Y_AXIS-VAL
          BI_Y_AXIS
          BI_Z_AXIS-VAL
          BI_Z_AXIS
          BI_ERROR-VAL
          BI_ERROR
          BI_STATUS-VAL
          BI_STATUS
          WS_TRANSVERSE-VAL
          WS_TRANSVERSE
          WS_LONGITUDINAL-VAL
          WS_LONGITUDINAL
          WS_NORMAL-VAL
          WS_NORMAL
          WS_STATUS-VAL
          WS_STATUS
          BS_TRANSVERSE-VAL
          BS_TRANSVERSE
          BS_LONGITUDINAL-VAL
          BS_LONGITUDINAL
          BS_NORMAL-VAL
          BS_NORMAL
          BS_STATUS-VAL
          BS_STATUS
          WE_EAST-VAL
          WE_EAST
          WE_NORTH-VAL
          WE_NORTH
          WE_UPWARDS-VAL
          WE_UPWARDS
          WE_STATUS-VAL
          WE_STATUS
          BE_EAST-VAL
          BE_EAST
          BE_NORTH-VAL
          BE_NORTH
          BE_UPWARDS-VAL
          BE_UPWARDS
          BE_STATUS-VAL
          BE_STATUS
          WD_EAST-VAL
          WD_EAST
          WD_NORTH-VAL
          WD_NORTH
          WD_UPWARDS-VAL
          WD_UPWARDS
          WD_RANGE-VAL
          WD_RANGE
          WD_TIME-VAL
          WD_TIME
          BD_EAST-VAL
          BD_EAST
          BD_NORTH-VAL
          BD_NORTH
          BD_UPWARDS-VAL
          BD_UPWARDS
          BD_RANGE-VAL
          BD_RANGE
          BD_TIME-VAL
          BD_TIME
          RAW_DATA-VAL
          RAW_DATA
))