set(_CATKIN_CURRENT_PACKAGE "osg_utils")
set(osg_utils_VERSION "1.0.2")
set(osg_utils_MAINTAINER "Javier Perez <japerez@uji.es>")
set(osg_utils_PACKAGE_FORMAT "1")
set(osg_utils_BUILD_DEPENDS "roscpp" "libopenscenegraph" "geometry_msgs" "tf")
set(osg_utils_BUILD_EXPORT_DEPENDS "roscpp" "libopenscenegraph" "geometry_msgs" "tf")
set(osg_utils_BUILDTOOL_DEPENDS "catkin")
set(osg_utils_BUILDTOOL_EXPORT_DEPENDS )
set(osg_utils_EXEC_DEPENDS "roscpp" "libopenscenegraph" "geometry_msgs" "tf")
set(osg_utils_RUN_DEPENDS "roscpp" "libopenscenegraph" "geometry_msgs" "tf")
set(osg_utils_TEST_DEPENDS )
set(osg_utils_DOC_DEPENDS )
set(osg_utils_DEPRECATED "")