set(_CATKIN_CURRENT_PACKAGE "liftdragww")
set(liftdragww_VERSION "0.0.0")
set(liftdragww_MAINTAINER "lsa <lsa@todo.todo>")
set(liftdragww_PACKAGE_FORMAT "1")
set(liftdragww_BUILD_DEPENDS "roscpp" "std_msgs")
set(liftdragww_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(liftdragww_BUILDTOOL_DEPENDS "catkin")
set(liftdragww_BUILDTOOL_EXPORT_DEPENDS )
set(liftdragww_EXEC_DEPENDS "roscpp" "std_msgs")
set(liftdragww_RUN_DEPENDS "roscpp" "std_msgs")
set(liftdragww_TEST_DEPENDS )
set(liftdragww_DOC_DEPENDS )
set(liftdragww_DEPRECATED "")