set(_CATKIN_CURRENT_PACKAGE "uwsim")
set(uwsim_VERSION "1.4.1")
set(uwsim_MAINTAINER "Mario Prats <marioprats@gmail.com>, Javier Perez <perezsolerj@gmail.com>")
set(uwsim_PACKAGE_FORMAT "1")
set(uwsim_BUILD_DEPENDS "boost" "geometry_msgs" "image_transport" "interactive_markers" "kdl_parser" "libopenscenegraph" "libxml++-2.6" "nav_msgs" "opengl" "osg_interactive_markers" "osg_markers" "osg_utils" "pcl_ros" "pluginlib" "resource_retriever" "robot_state_publisher" "roscpp" "sensor_msgs" "tf" "urdf" "underwater_sensor_msgs" "uwsim_bullet" "uwsim_osgbullet" "uwsim_osgocean" "uwsim_osgworks" "xacro")
set(uwsim_BUILD_EXPORT_DEPENDS "boost" "geometry_msgs" "image_transport" "interactive_markers" "kdl_parser" "libopenscenegraph" "libxml++-2.6" "nav_msgs" "opengl" "osg_interactive_markers" "osg_markers" "osg_utils" "pcl_ros" "pluginlib" "resource_retriever" "robot_state_publisher" "roscpp" "sensor_msgs" "tf" "urdf" "underwater_sensor_msgs" "uwsim_bullet" "uwsim_osgbullet" "uwsim_osgocean" "uwsim_osgworks" "xacro")
set(uwsim_BUILDTOOL_DEPENDS "catkin")
set(uwsim_BUILDTOOL_EXPORT_DEPENDS )
set(uwsim_EXEC_DEPENDS "boost" "geometry_msgs" "image_transport" "interactive_markers" "kdl_parser" "libopenscenegraph" "libxml++-2.6" "nav_msgs" "opengl" "osg_interactive_markers" "osg_markers" "osg_utils" "pcl_ros" "pluginlib" "resource_retriever" "robot_state_publisher" "roscpp" "sensor_msgs" "tf" "urdf" "underwater_sensor_msgs" "uwsim_bullet" "uwsim_osgbullet" "uwsim_osgocean" "uwsim_osgworks" "xacro")
set(uwsim_RUN_DEPENDS "boost" "geometry_msgs" "image_transport" "interactive_markers" "kdl_parser" "libopenscenegraph" "libxml++-2.6" "nav_msgs" "opengl" "osg_interactive_markers" "osg_markers" "osg_utils" "pcl_ros" "pluginlib" "resource_retriever" "robot_state_publisher" "roscpp" "sensor_msgs" "tf" "urdf" "underwater_sensor_msgs" "uwsim_bullet" "uwsim_osgbullet" "uwsim_osgocean" "uwsim_osgworks" "xacro")
set(uwsim_TEST_DEPENDS )
set(uwsim_DOC_DEPENDS )
set(uwsim_DEPRECATED "")