#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/lsa/ocean2/devel_isolated/uwsim:/home/lsa/ocean2/devel_isolated/underwater_vehicle_dynamics:/home/lsa/ocean2/devel_isolated/underwater_sensor_msgs:/home/lsa/ocean2/devel_isolated/osg_interactive_markers:/home/lsa/ocean2/devel_isolated/osg_utils:/home/lsa/ocean2/devel_isolated/osg_markers:/home/lsa/ocean2/devel_isolated/liftdragww:/home/lsa/ocean2/devel_isolated/freefloating_gazebo_demo:/home/lsa/ocean2/devel_isolated/freefloating_gazebo:/home/lsa/ocean2/devel_isolated/first_control:/opt/ros/kinetic:/home/lsa/ocean2/devel_isolated/uwsim_osgbullet:/home/lsa/ocean2/devel_isolated/uwsim_osgworks:/home/lsa/ocean2/devel_isolated/uwsim_osgocean:/home/lsa/ocean2/devel_isolated/uwsim_bullet"
export LD_LIBRARY_PATH="/home/lsa/ocean2/devel_isolated/uwsim/lib:/home/lsa/ocean2/devel_isolated/underwater_vehicle_dynamics/lib:/home/lsa/ocean2/devel_isolated/underwater_sensor_msgs/lib:/home/lsa/ocean2/devel_isolated/osg_interactive_markers/lib:/home/lsa/ocean2/devel_isolated/osg_utils/lib:/home/lsa/ocean2/devel_isolated/osg_markers/lib:/home/lsa/ocean2/devel_isolated/liftdragww/lib:/home/lsa/ocean2/devel_isolated/freefloating_gazebo_demo/lib:/home/lsa/ocean2/devel_isolated/freefloating_gazebo/lib:/home/lsa/ocean2/devel_isolated/first_control/lib:/opt/ros/kinetic/lib:/home/lsa/ocean2/devel_isolated/uwsim_osgbullet/lib:/home/lsa/ocean2/devel_isolated/uwsim_osgbullet/lib/x86_64-linux-gnu:/home/lsa/ocean2/devel_isolated/uwsim_osgworks/lib:/home/lsa/ocean2/devel_isolated/uwsim_osgworks/lib/x86_64-linux-gnu:/home/lsa/ocean2/devel_isolated/uwsim_osgocean/lib:/home/lsa/ocean2/devel_isolated/uwsim_osgocean/lib/x86_64-linux-gnu:/home/lsa/ocean2/devel_isolated/uwsim_bullet/lib:/home/lsa/ocean2/devel_isolated/uwsim_bullet/lib/x86_64-linux-gnu"
export PATH="/opt/ros/kinetic/bin:/home/lsa/ocean2/devel_isolated/uwsim_osgbullet/bin:/home/lsa/ocean2/devel_isolated/uwsim_osgworks/bin:/home/lsa/ocean2/devel_isolated/uwsim_osgocean/bin:/home/lsa/ocean2/devel_isolated/uwsim_bullet/bin:/home/lsa/bin:/home/lsa/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
export PKG_CONFIG_PATH="/home/lsa/ocean2/devel_isolated/uwsim/lib/pkgconfig:/home/lsa/ocean2/devel_isolated/underwater_vehicle_dynamics/lib/pkgconfig:/home/lsa/ocean2/devel_isolated/underwater_sensor_msgs/lib/pkgconfig:/home/lsa/ocean2/devel_isolated/osg_interactive_markers/lib/pkgconfig:/home/lsa/ocean2/devel_isolated/osg_utils/lib/pkgconfig:/home/lsa/ocean2/devel_isolated/osg_markers/lib/pkgconfig:/home/lsa/ocean2/devel_isolated/liftdragww/lib/pkgconfig:/home/lsa/ocean2/devel_isolated/freefloating_gazebo_demo/lib/pkgconfig:/home/lsa/ocean2/devel_isolated/freefloating_gazebo/lib/pkgconfig:/home/lsa/ocean2/devel_isolated/first_control/lib/pkgconfig:/opt/ros/kinetic/lib/pkgconfig:/home/lsa/ocean2/devel_isolated/uwsim_osgbullet/lib/pkgconfig:/home/lsa/ocean2/devel_isolated/uwsim_osgbullet/lib/x86_64-linux-gnu/pkgconfig:/home/lsa/ocean2/devel_isolated/uwsim_osgworks/lib/pkgconfig:/home/lsa/ocean2/devel_isolated/uwsim_osgworks/lib/x86_64-linux-gnu/pkgconfig:/home/lsa/ocean2/devel_isolated/uwsim_osgocean/lib/pkgconfig:/home/lsa/ocean2/devel_isolated/uwsim_osgocean/lib/x86_64-linux-gnu/pkgconfig:/home/lsa/ocean2/devel_isolated/uwsim_bullet/lib/pkgconfig:/home/lsa/ocean2/devel_isolated/uwsim_bullet/lib/x86_64-linux-gnu/pkgconfig"
export PYTHONPATH="/home/lsa/ocean2/devel_isolated/underwater_sensor_msgs/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages:/home/lsa/ocean2/devel_isolated/uwsim_osgbullet/lib/python2.7/dist-packages:/home/lsa/ocean2/devel_isolated/uwsim_osgworks/lib/python2.7/dist-packages:/home/lsa/ocean2/devel_isolated/uwsim_osgocean/lib/python2.7/dist-packages:/home/lsa/ocean2/devel_isolated/uwsim_bullet/lib/python2.7/dist-packages"
export ROSLISP_PACKAGE_DIRECTORIES="/home/lsa/ocean2/devel_isolated/uwsim/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/lsa/ocean2/src/underwater_simulation/uwsim:$ROS_PACKAGE_PATH"