// Generated by gencpp from file underwater_sensor_msgs/SpawnMarker.msg
// DO NOT EDIT!


#ifndef UNDERWATER_SENSOR_MSGS_MESSAGE_SPAWNMARKER_H
#define UNDERWATER_SENSOR_MSGS_MESSAGE_SPAWNMARKER_H

#include <ros/service_traits.h>


#include <underwater_sensor_msgs/SpawnMarkerRequest.h>
#include <underwater_sensor_msgs/SpawnMarkerResponse.h>


namespace underwater_sensor_msgs
{

struct SpawnMarker
{

typedef SpawnMarkerRequest Request;
typedef SpawnMarkerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpawnMarker
} // namespace underwater_sensor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::underwater_sensor_msgs::SpawnMarker > {
  static const char* value()
  {
    return "a7395a01b635e68c485c6bc7fed0b5a1";
  }

  static const char* value(const ::underwater_sensor_msgs::SpawnMarker&) { return value(); }
};

template<>
struct DataType< ::underwater_sensor_msgs::SpawnMarker > {
  static const char* value()
  {
    return "underwater_sensor_msgs/SpawnMarker";
  }

  static const char* value(const ::underwater_sensor_msgs::SpawnMarker&) { return value(); }
};


// service_traits::MD5Sum< ::underwater_sensor_msgs::SpawnMarkerRequest> should match 
// service_traits::MD5Sum< ::underwater_sensor_msgs::SpawnMarker > 
template<>
struct MD5Sum< ::underwater_sensor_msgs::SpawnMarkerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::underwater_sensor_msgs::SpawnMarker >::value();
  }
  static const char* value(const ::underwater_sensor_msgs::SpawnMarkerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::underwater_sensor_msgs::SpawnMarkerRequest> should match 
// service_traits::DataType< ::underwater_sensor_msgs::SpawnMarker > 
template<>
struct DataType< ::underwater_sensor_msgs::SpawnMarkerRequest>
{
  static const char* value()
  {
    return DataType< ::underwater_sensor_msgs::SpawnMarker >::value();
  }
  static const char* value(const ::underwater_sensor_msgs::SpawnMarkerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::underwater_sensor_msgs::SpawnMarkerResponse> should match 
// service_traits::MD5Sum< ::underwater_sensor_msgs::SpawnMarker > 
template<>
struct MD5Sum< ::underwater_sensor_msgs::SpawnMarkerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::underwater_sensor_msgs::SpawnMarker >::value();
  }
  static const char* value(const ::underwater_sensor_msgs::SpawnMarkerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::underwater_sensor_msgs::SpawnMarkerResponse> should match 
// service_traits::DataType< ::underwater_sensor_msgs::SpawnMarker > 
template<>
struct DataType< ::underwater_sensor_msgs::SpawnMarkerResponse>
{
  static const char* value()
  {
    return DataType< ::underwater_sensor_msgs::SpawnMarker >::value();
  }
  static const char* value(const ::underwater_sensor_msgs::SpawnMarkerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNDERWATER_SENSOR_MSGS_MESSAGE_SPAWNMARKER_H
